name: perspec
version: 0.2.0.0
github: feramhq/Perspec
license-file: license
author: Adrian Sieber
maintainer: mail@adriansieber.com
copyright: Adrian Sieber

extra-source-files:
  - readme.md
  - changelog.md

synopsis: Scan documents and books with as little hardware as possible.
category: Scan

description: |
  Please see the readme on GitHub at <https://github.com/feramhq/Perspec#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bmp
  - bytestring
  - directory
  - docopt
  - file-embed
  - filepath
  - gloss
  - gloss-juicy
  - hsexif
  - JuicyPixels
  - natural-sort
  - process
  - protolude
  - text
  - yaml

default-extensions:
  - DeriveGeneric
  - LambdaCase
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-orphans

library:
  source-dirs: source

executables:
  perspec:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - perspec

tests:
  perspec-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - perspec
