# Only update to lts-23 once HLS supports GHC 9.8.4
# https://haskell-language-server.readthedocs.io/en/latest/support/ghc-version-support.html
resolver: lts-23.18

packages:
  - .

extra-deps:
  - docopt-0.7.0.8

  - github: lehins/hip
    commit: ddfc77feb21722babccd3b3aa73c4c3d41268f54
    subdirs:
      - hip

  - github: lehins/Color
    commit: ec833edd8f9b15543855c00826c4ede470773f83
    subdirs:
      - Color

  - github: ad-si/Brillo
    commit: ab2dc5244194d184740c5d0de909669141dd1313
    subdirs:
      - brillo
      - brillo-algorithms
      - brillo-juicy
      - brillo-rendering

allow-newer: true
