# Check if HLS supports the LTS release before upgrading
# and also set the correct GHC version in `flake.nix`.
# https://haskell-language-server.readthedocs.io/en/latest/support/ghc-version-support.html
resolver: lts-23.27

# Necessary as the Nix Flake sets the GHC version
system-ghc: true

packages:
  - .

extra-deps:
  - docopt-0.7.0.8
  - flatcv-0.3.0.1
  - storable-offset-0.1.0.0
  - webp-0.1.2.0

  - github: lehins/hip
    commit: ddfc77feb21722babccd3b3aa73c4c3d41268f54
    subdirs:
      - hip

  - github: lehins/Color
    commit: ec833edd8f9b15543855c00826c4ede470773f83
    subdirs:
      - Color

  - github: ad-si/Brillo
    commit: f3ac5d54d9f007bb94c475eae1ddd53ba59a97d9
    subdirs:
      - brillo
      - brillo-algorithms
      - brillo-juicy
      - brillo-rendering

  - github: dpwiz/freetype2
    commit: d2acf926b5c448d8edd60e322862adcf2dbe9146

  - github: bsl/bindings-GLFW
    commit: a98990a882da8f2cb3ff6730d614f5d37adbde33

allow-newer: true
